name: Android Build

on: pull_request

jobs:
  test:
    name: Run Test Suite
    runs-on: macos-latest
    steps:
      - name: Clone Repo
          uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Unit Tests
        run: ./gradlew testDebug --tests="*.ExampleUnitTest"

